### ISSUE TITLE
类成员函数作为消息处理函数

### ISSUE THREAD

**Issue by weberwang** [whtsky/WeRoBot#157]
文档给出的例子是
`import werobot

robot = werobot.WeRoBot(token='tokenhere')

@robot.handler
def echo(message):
    return 'Hello World!'

robot.run()`
以下场景不能满足
`import werobot
robot = werobot.WeRoBot(token='tokenhere')
class Message():

    @robot.handler
    def echo(self, message):
        return 'Hello World!'`
#156

**Comment by whtsky** [comment]
把这个 handler 写成 class method 的意义是什么？

**Comment by whtsky** [comment]
@weberwang 你这样获取到的是一个 unbound method , self 参数根本获取不到有意义的东西啊
