### ISSUE TITLE
Semaphoreci may sometimes seize up

### ISSUE THREAD

**Issue by helloqiu** [whtsky/WeRoBot#159]
It can sometimes seize up during the tests with **pypy** and after refreshing the page all of the logs disappear.
 But when the tests finally stop the logs will come back and end up with something like this:
```
...
collecting 54 items
collecting 58 itemsexecution expired
```
I run **tox** successfully on my PC. 
An example: [https://semaphoreci.com/whtsky/werobot/branches/pull-request-156/builds/3](https://semaphoreci.com/whtsky/werobot/branches/pull-request-156/builds/3)

**Comment by whtsky** [comment]
这不应该联系 Semaphoreci 吗。。

**Comment by helloqiu** [comment]
发在这引用啊（

**Comment by helloqiu** [comment]
那我去 Semaphoreci 反馈了（

**Comment by whtsky** [comment]
讲道理 Semaphoreci 的客服态度非常好
我上次吐槽他们没有 python2.6-dev ，他们很愉快的表示我们知道了
然后就没有然后了
