### ISSUE TITLE
目前是否支持发现金红包？

### ISSUE THREAD

**Issue by ruocao** [whtsky/WeRoBot#161]
您好，我查看了API文档，但没有发现有相关的API，微信官方的开发文档是提供的有这个接口的（https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon.php?chapter=13_1）。

**Comment by whtsky** [comment]
不支持，欢迎发 PR

**Comment by whtsky** [comment]
不支持，欢迎发 PR

**Comment by whtsky** [comment]
不支持，欢迎发 PR

**Comment by ruocao** [comment]
好的，感谢回复，等我把其他部分的逻辑写完看看源码: )
