### ISSUE TITLE
请问回复类型为什么没有图片？

### ISSUE THREAD

**Issue by fiht** [whtsky/WeRoBot#165]
仔细研读了一下文档，发现只有TextReply ， ArticlesReply ， MusicReply和TransferCustomerServiceReply，我想要实现的是对方发送一条消息我给对方回复一个搞笑的图片。
不知道各位大佬有什么建议。

**Comment by helloqiu** [comment]
新版有
[https://github.com/whtsky/WeRoBot/blob/develop/docs/replies.rst#imagereply](https://github.com/whtsky/WeRoBot/blob/develop/docs/replies.rst#imagereply)
