### ISSUE TITLE
WeRoBot doesn't handle duplicate messages.

### ISSUE THREAD

**Issue by prikevs** [whtsky/WeRoBot#167]
https://mp.weixin.qq.com/wiki/10/79502792eef98d6e0c6e1739da387346.html
According to the document above. The server of WeChat may retry to send duplicate messages to the framework if I don't send back result in 5 sec due to some time-consuming work.

I find that werobot doesn't handle duplicate messages in framework level. And I tried to use session to filter duplicate messages by message.id but session only commits when the handler finished.

So I think it is necessary to implement framework-level duplicate messages filter. Do you have any idea?

**Comment by helloqiu** [comment]
https://github.com/whtsky/WeRoBot/blob/develop/docs/replies.rst#successreply
Check this.
