### ISSUE TITLE
微信回复更新

### ISSUE THREAD

**Issue by NewPasser** [whtsky/WeRoBot#168]
消息管理-发送消息-被动回复用户消息
在微信文档里面https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140543&token=&lang=zh_CN
被动回复有6种.
你这里面(https://werobot.readthedocs.io/zh_CN/latest/replies.html)的回复只支持了三种(文本,文章,音乐),近期是否会支持另外的三种(语音,视频,图片)

**Comment by helloqiu** [comment]
现在的 develop 分支已经有了，会在 1.0 版本中更新。
https://github.com/whtsky/WeRoBot/blob/develop/docs/replies.rst
