### ISSUE TITLE
AttributeError: 'module' object has no attribute 'WeRoBot'

### ISSUE THREAD

**Issue by shineforever** [whtsky/WeRoBot#175]
In [1]: import werobot

In [2]: robot = werobot.WeRoBot(token='tokenhere')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-bca709e452ae> in <module>()
----> 1 robot = werobot.WeRoBot(token='tokenhere')

AttributeError: 'module' object has no attribute 'WeRoBot'

环境：Python 2.7.12

**Comment by yuzhou6** [comment]
同上，有使用这框架的朋友也碰到了这个问题。

**Comment by qwe14789cn** [comment]
用py3 就行了

**Comment by ccw55ccw** [comment]
我也遇到了  同求

**Comment by whtsky** [comment]
![image](https://cloud.githubusercontent.com/assets/876694/20865691/31f5102c-ba54-11e6-96e1-1519ca7364c1.png)
我似乎不能复现这个问题…… 能贴一下 `from werobot.robot import WeRoBot` 的报错嘛？
cc @ccw55ccw @shineforever @yuzhou6

**Comment by whtsky** [comment]
似乎是打包的问题…… 
运行 `pip install funcsigs` 可以解决

**Comment by Sowevo** [comment]
知道了,你写的文件名是不是叫**werobot.py**,然后**import werobot**的时候就出问题了的样子

**Comment by autodataming** [comment]
推荐使用anaconda python 就不会出现上述问题，linux 自带python 受yum 管理，不够灵活。

**Comment by xu4wang** [comment]
[austin@support WeRoBot]$ python
Python 2.7.10 (default, Sep  6 2018, 02:07:39)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import werobot
>>> werobot.WeRoBot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'WeRoBot'
>>>

**Comment by xu4wang** [comment]
这个问题该怎么解决呢？ Python是2.7.10重现了。

**Comment by xu4wang** [comment]
已经解决了。我这里出问题的原因是系统中有两个python。PIP装到一个python下面， 命令行运行python是另外一个。

**Comment by wxwmd** [comment]
感谢楼主，我也是这个问题
