### ISSUE TITLE
请问下werobot支持blueprint功能吗？

### ISSUE THREAD

**Issue by jachinlin** [whtsky/WeRoBot#178]

**Comment by helloqiu** [comment]
是指 Flask 的 Blueprint 吗？
如果是的话，支持。
@jachinlin

**Comment by helloqiu** [comment]
也许你是在找这个。
http://flask.pocoo.org/docs/0.12/api/#flask.Blueprint.add_url_rule
https://werobot.readthedocs.io/zh_CN/latest/contrib.html#flask
@jachinlin

**Comment by jachinlin** [comment]
谢谢
