### ISSUE TITLE
默认enable_session=True的一点副作用

### ISSUE THREAD

**Issue by jxltom** [whtsky/WeRoBot#189]
因为默认```enable_session=True```和```session_storage=None```, 初始化WeRoBot时```session_storage = SQLiteStorage()```, 这将产生一个名为```werobot_session.sqlite3```的数据库. 即使之后设置```robot.config['SESSION_STORAGE'] = None```, 这个文件也已经产生.

这意味着无法直接利用```Config```完全控制WeRoBot, 如果想关闭session并不产生多余数据库, 必须在初始化时传入```enable_session=False```, 无法仅仅通过```Config```类控制.

WeRoBot很好用, 以上仅仅是使用中感觉有一点别扭的地方, thanks.

**Comment by whtsky** [comment]
打算把 SessionStorage 也放在 Config 里面…… 然后 deprecate 掉 enable_session
想想怎么做比较好

**Comment by jxltom** [comment]
或许可以直接利用SESSION_STORAGE开启session

```SESSION_STORAGE = None``` 时, session disabled.
```SESSION_STORAGE = SQLiteStorage | RedisStorage | ...```, session enabled.

By default,  session is disabled.

**Comment by whtsky** [comment]
是打算直接用 SESSION_STORAGE 控制开启/关闭
不过默认关闭的话就是比较大的 break change 了，感觉在 1.0.0 -> 1.1.0 的时候搞 break change 不太好

**Comment by whtsky** [comment]
现在 session_storage 在第一次被访问的时候才会被初始化了， 所以
```python
robot = WeRoBot()
robot.config['SESSION_STORAGE'] = None
```

不会再生成 SQLite 文件了。

另外也可以先生成 config ，再传给 WeRoBot 了
```python
config = Config()
robot = WeRoBot(config=config)
```
