### ISSUE TITLE
Missing werobot/contrib/error.html in PyPI source

### ISSUE THREAD

**Issue by jxltom** [whtsky/WeRoBot#194]
The file ```werobot/contrib/error.html``` in ```WeRoBot-1.0.0.zip``` and ```WeRoBot-1.0.0.tar.gz``` of [WeRoBot 1.0.0](https://pypi.python.org/pypi/WeRoBot/1.0.0) is missing.

This causes no error page for werobot installed by ```pip install werobot```.

Installing by ```pip install git+https://github.com/whtsky/WeRoBot.git@v1.0.0``` can solve this issue temporarily.

**Comment by helloqiu** [comment]
The `error.html` is ignored during packaging.
Maybe you can write a custom error page with **@robot.error_page** temporarily.
@jxltom

**Comment by jxltom** [comment]
OK. Thanks!
