### ISSUE TITLE
Client.send_music_message 缩略图的问题

### ISSUE THREAD

**Issue by wwj718** [whtsky/WeRoBot#197]
hi 大家好， 我在调用WeRoBot的Client.send_music_message时，发送成功了，也收到了音乐，不过没有缩略图（缩略图已经成功上传微信，得到media_id），不过，获得的音乐也没有缩略图。  我直接按照微信官方文档的http请求推送，获得的音乐也没有缩略图，是微信api的bug吗

**Comment by wwj718** [comment]
另 werobot版本用的是1.1.0，旧版本也试过，没区别

**Comment by helloqiu** [comment]
求上传和发消息的代码
@wwj718

**Comment by wwj718** [comment]
`werobot_client.send_music_message(user_id=openid,url=url,hq_url=hq_url,thumb_media_id=media_id, title="test", description="test")`
media_id检验过没问题，使用`Client.send_music_message`发送图片时没问题的

**Comment by helloqiu** [comment]
用微信的接口调试试了一下，感觉是微信的问题，你也可以用这个试试。
https://mp.weixin.qq.com/debug/cgi-bin/apiinfo?t=index&type=%E5%9F%BA%E7%A1%80%E6%94%AF%E6%8C%81&form=%E4%B8%8B%E8%BD%BD%E5%A4%9A%E5%AA%92%E4%BD%93%E6%96%87%E4%BB%B6%E6%8E%A5%E5%8F%A3%20/media/get
@wwj718

**Comment by wwj718** [comment]
@helloqiu, 感谢这个我也试过了 应该是微信的问题
