### ISSUE TITLE
能否把消息处理的部分分离出去

### ISSUE THREAD

**Issue by JamesLiAndroid** [whtsky/WeRoBot#198]
首先感谢作者的框架，确实减少了开发工作！

然后我想说的是，当我将消息处理函数放到另外一个.py文件中，并且在该文件中导入了robot，如下：

msg.py
`from run import robot
from core.logger_helper import logger

import sys

reload(sys)
sys.setdefaultencoding('utf8')

@robot.handler
def subscribe(message):
    return '欢迎来到小李的时代！'
`

run.py
`from werobot import WeRoBot
from werobot.contrib.tornado import make_handler
from config import my_config

import sys
reload(sys)
sys.setdefaultencoding("utf-8")

robot = WeRoBot(config = my_config)`

运行整个项目以后，发现出现下面的日志：
WARNING:WeRoBot:No handler responded message <werobot.messages.messages.TextMessage object at 0x7f4343ade910>

而公众号无法做出回复。

想问一下这种情况如何解决？

**Comment by helloqiu** [comment]
https://werobot.readthedocs.io/zh_CN/latest/handlers.html#handler
你好像没有 **add_handler** ? @JamesLiAndroid

**Comment by helloqiu** [comment]
运行的是 **run.py** 吗？如果是的话感觉 **msg.py** 里面的代码并不会影响到 **run.py** 里面的 WeRoBot 对象。
如果想要把 WeRoBot 对象和 handler 分离到不同的文件，感觉可以在 **msg.py** 里面定义普通的方法之后在 **run.py** 内用 **add_handler** 添加。
@JamesLiAndroid

**Comment by JamesLiAndroid** [comment]
这个思路确实可以，但是如果存在@robot.filter('abc')这样的装饰器，这个方式还可行吗？

例如，我现在对**“天气”**进行单独的回复，这样我只能在add_handler方法中指定type=‘text'，然后在该方法下通过if-else进行判断？

**Comment by helloqiu** [comment]
如果是 **WeRoBot.filter** 的话应该就暂时不行了，感觉缺少一个 **add_filter** 这样的接口。
另外其实 **WeRoBot.filter** 的现在的实现和你上面讲的差不多：
https://github.com/whtsky/WeRoBot/blob/develop/werobot/robot.py#L282
但感觉实现的并不优雅，感觉需要在下个版本里面改进。
@JamesLiAndroid

**Comment by JamesLiAndroid** [comment]
还存在一个问题，前后两个方法在add_handler时都指定为text类型的，后一个方法会被前一个方法所屏蔽，导致原本属于后一个方法处理的内容被前一个方法捕获，导致消息不能被处理

**Comment by helloqiu** [comment]
这是 intended 的，只有前一个返回了 ```None``` 或者 ```False``` 才会让后一个 handler 处理。
因为我们认为一个消息只应该对应一个 handler 处理并只有一个回复，当收到消息之后 WeRoBot 会首先根据消息的类型得到所有的 handler，然后遍历每一个 handler，如果当前 handler 有回复即代表了这个消息应该由这个 handler 来处理，所以并不会再运行之后的 handler。
@JamesLiAndroid

**Comment by JamesLiAndroid** [comment]
恩，明白了，感谢讲解！

**Comment by whtsky** [comment]
@helloqiu 感觉可以加一个 `add_filter` 来应对这种情况？
