### ISSUE TITLE
LinkMessage是指什么类型的消息？

### ISSUE THREAD

**Issue by yacogo** [whtsky/WeRoBot#200]
我尝试往公众号发送过链接，但是服务器端将这个消息认为TextMessage

**Comment by helloqiu** [comment]
https://mp.weixin.qq.com/wiki/17/f298879f8fb29ab98b2f2971d42552fd.html#.E9.93.BE.E6.8E.A5.E6.B6.88.E6.81.AF
比如朋友圈里各种广告链接收藏后发给公众号就是 LinkMessage。
@yacogo
