### ISSUE TITLE
get_media_list这个函数中，发送的参数错误

### ISSUE THREAD

**Issue by lovesecho** [whtsky/WeRoBot#208]
参考https://mp.weixin.qq.com/wiki/15/8386c11b7bc4cdd1499c572bfe2e95b3.html
三个参数分别是type offset count
代码中是：
        return self.post(
            url="https://api.weixin.qq.com/cgi-bin/material/batchget_material",
            data={
                "media": media_type,
                "offset": offset,
                "count": count
            }
        )

**Comment by wdnlwzd** [comment]
请问 media 参数6个月前就已经修正为 type了，为什么通过 pip 安装的 最新版（v1.1.1）， 
![image](https://user-images.githubusercontent.com/17924984/30585838-a57fe2de-9d60-11e7-8d46-6b130c1dd1d6.png)

参数仍然是 media , 导致获取列表报错。没 merge 到 master ? @whtsky

**Comment by whtsky** [comment]
还没 release ，可以装 develop 分支的版本。

**Comment by wdnlwzd** [comment]
ok, 谢谢
