### ISSUE TITLE
怎么清除session？比如我要清除某一个微信用户的session，用自带的delete()不管用啊

### ISSUE THREAD

**Issue by LJerRRy** [whtsky/WeRoBot#226]
除了标题问题外，还有就是为啥session是个字典，我将session赋值为{}，不能生效，而session[s] =“” for s in session反而生效了？
我用的是sqlite3作为session数据库，自己修改session数据库怎么不生效

**Comment by whtsky** [comment]
麻烦提供复现代码，谢谢

**Comment by helloqiu** [comment]
Close due to no response.
