### ISSUE TITLE
ImageMessage消息体的问题

### ISSUE THREAD

**Issue by Hu1-Li** [whtsky/WeRoBot#227]
官方的Image消息的消息体是这样给的

> ToUserName	开发者微信号
FromUserName	发送方帐号（一个OpenID）
CreateTime	消息创建时间 （整型）
MsgType	image
PicUrl	图片链接（由系统生成）
MediaId	图片消息媒体id，可以调用多媒体文件下载接口拉取数据。
MsgId	消息id，64位整型

但是WeRoBot里面的消息体是这样的

> type	‘image’
img	图片网址。你可以从这个网址下到图片

所以设计时候为什么会选择丢弃这个字段(MediaId)

**Comment by helloqiu** [comment]
![image](https://user-images.githubusercontent.com/8971659/30206173-cde8770a-94bd-11e7-9d41-2301cc21f7d0.png)
https://werobot.readthedocs.io/zh_CN/latest/messages.html#id1
https://werobot.readthedocs.io/zh_CN/latest/messages.html#imagemessage
