### ISSUE TITLE
flask的阿里云部署问题

### ISSUE THREAD

**Issue by journeyly** [whtsky/WeRoBot#234]
我是小白，想通过werobot学习如何部署。但是没看懂，所以求教。
首先，我参考flask写了一个最基本的页面app.py，部署成功了，输入地址能访问。
…………………………………………
# Filename: app.py
from flask import Flask
app = Flask(__name__)
 @app.route("/")
def hello():
    return "Hello World!"
………………………………………………
然后，我就想参考你的案例部署werobot，先在网站的根目录下创建了一个叫robot的文件夹，里面放了robot.py，token改成自己的微信公众号的了。
……………………………………………………
# Filename: robot.py
from werobot import WeRoBot
robot = WeRoBot(token='改了')
@robot.handler
def hello(message):
    return 'Hello World!'
………………………………………………
再然后，我把app.py按照你的修改了。之后网页就不能访问了，而且微信的token也一直验证失败。是不是WeRoBot 的绑定地址 这里出了什么问题？
我现在就想写在一个文件里（app.py），不单独写一个robot.py再引用，请问我应该如何写？
谢谢
………………………………………………
from werobot import WeRoBot
robot = WeRoBot(token='改了')
@robot.handler
def hello(message):
    return 'Hello World!'

from flask import Flask
from werobot.contrib.flask import make_view

app = Flask(__name__)
app.add_url_rule(rule='/robot/', # WeRoBot 的绑定地址
                endpoint='werobot', # Flask 的 endpoint
                view_func=make_view(robot),
                methods=['GET', 'POST'])
………………………………………………

**Comment by whtsky** [comment]
请提供完整的可复现代码和报错提示。

**Comment by journeyly** [comment]
您好，我贴的是完整的代码，按照您的教程写的，错误就是网络访问不了，token验证失败

**Comment by whtsky** [comment]
1. 不是完整代码，完全没有目录结构和缩进
2. WeRoBot 的测试包含 Flask 集成的相关代码，建议参考
3. token 验证失败检查 token 和相关日志

**Comment by journeyly** [comment]
谢谢的回答，好快！
以下是我的整个目录结构。然后我改的就是manage.py，如果是运行一个最简答的flask的hello world是可以访问的（问题最开始的时候贴的代码）。
然后我现在就是想把manage.py改成werobot的，只是想做简单的回复，这个参考了你的说明文档的代码。但是网络不通了，所以token才会失败。

www/
└── my_flask  
│   ├── logs
│   └── venv  //虚拟目录
│   │   ├── bin
│   │   │         ├── activate
│   │   │         ├── easy_install
│   │   │         ├── gunicorn
│   │   │         ├── pip
│   │   │         └── python
│   │   ├── include
│   │   │          └── python2.7 -> /usr/include/python2.7
│   │   ├── lib
│   │   │         └── python2.7
│   │   ├── local
│   │   │         ├── bin -> /home/shenye/shenyefuli/bin
│   │   │         ├── include -> /home/shenye/shenyefuli/include
│   │   │         └── lib -> /home/shenye/shenyefuli/lib
│   └── app  //Flask 程序目录
│   │           └──  __init__.py 
│   ├── manage.py	
│   ├── requirements.txt

**Comment by helloqiu** [comment]
配置 uWSGI 比较繁琐，新手不太容易配置，建议先用 gunicorn 跑然后 nginx 反代
@journeyly

**Comment by journeyly** [comment]
@helloqiu 感谢，我找了一下uwsgi的日志，没找到。有一个朋友用的gunicorn配置的，然后跟我的情况也一下。访问网页就报错：Internal Server Error，token也验证失败。可能我们都是没看懂官方文档flask那一部分。我看之前也有一个人也提出了同样的问题。

**Comment by whtsky** [comment]
@journeyly 如果你确信是 WeRoBot 的问题，请把错误日志贴上来。
只说 Internal Server Error 我们完全没办法排错

**Comment by journeyly** [comment]
嗯，我正在看到底是啥原因，不是说是werobot的问题，可能是跟flask那里我没配置好

**Comment by journeyly** [comment]
@helloqiu @whtsky ，我按照你们说的，在热心群友的帮助下，用gunicorn部署成功了。感谢你们的回复。我是初学者，python都不怎么会。所以如果跟我一样情况的人，也是建议还是先用gunicorn，按照官方文档进行部署就可以。

**Comment by whtsky** [comment]
OTZ

**Comment by whtsky** [comment]
实话实说我没用 uWSGI 部署过…… @helloqiu 可能也没试过？
如果日后用 uWSGI 部署遇到了同样的问题的话麻烦贴一下日志，谢谢

**Comment by journeyly** [comment]
好的

**Comment by TAOYi92** [comment]
@journeyly 楼主你好，我也是小白，请问你在阿里云上部署的时候主要参考的是哪些资料呢？我尝试了很多网上的方案，到现在还没有成功。希望得到您的指点！谢谢！
