### ISSUE TITLE
sae部署问题

### ISSUE THREAD

**Issue by Helios-lmh** [whtsky/WeRoBot#235]
通过SVN把示例代码部署到sae上了，直接访问应用网址也会出现werobot的界面，公众号token也验证成功了，但是直接在公众号里发消息时回复是‘该公众号暂时无法提供服务，请稍后再试’。请问这是哪里出了问题呢？

**Comment by whtsky** [comment]
没有 handler 处理消息或者 handler 没有正确返回。

**Comment by Helios-lmh** [comment]
```
@robot.handler
def echo(message):
    return 'Hello World!'
```
这样对吗？

**Comment by whtsky** [comment]
对

**Comment by Helios-lmh** [comment]
可是公众号依然是无法提供服务，示例代码基本没有做改动就上传的。

**Comment by whtsky** [comment]
贴完整代码和服务器端日志

**Comment by Helios-lmh** [comment]
```
#filename:robot.py
import os
import sys

root = os.path.dirname(__file__)

sys.path.insert(0, os.path.join(root, 'werobot'))

import werobot

robot = werobot.WeRoBot(token='*********')

@robot.handler
def echo(message):
    return 'Hello World!'
```
filename:index.wsgi
```
import os
import sys
import sae
import web

from robot import robot
application = sae.create_wsgi_app(robot.wsgi)
```
filename:config.yaml
```
name: *****
worker: wsgi
version: 1
```
失败的日志
140.207.54.79 0.443 0.443 [10/Aug/2017:16:37:19 +0800] hang01 518 2 POST /?signature=4538ef565f61519c77b7a9ea90485a63986a59ee&timestamp=1502354239&nonce=771995136&openid=o_0YJwF5ECQofKyi4hMFSzn4RkQ8&encrypt_type=aes&msg_signature=97cefad2bfc7b98476c51e5e425938ada6ff42a3 HTTP/1.1 500 964 "-" "Mozilla/4.0" yq34

**Comment by whtsky** [comment]
没设置消息加解密
http://werobot.readthedocs.io/zh_CN/latest/encryption.html

**Comment by Helios-lmh** [comment]
上传了cryptography包，然后在robot.py里加了一句`robot.config['ENCODING_AES_KEY'] = 'Your Encoding AES Key'`，还是不行

日志
140.207.54.80 0.504 0.504 [10/Aug/2017:17:53:45 +0800] hang01 518 2 POST /?signature=4b3027d1cb235a7b35909265ef81b295f90f095f&timestamp=1502358824&nonce=1666778272&openid=o_0YJwF5ECQofKyi4hMFSzn4RkQ8 HTTP/1.1 500 885 "-" "Mozilla/4.0" yq26

**Comment by whtsky** [comment]
可能还得加一下 `APP_ID` ..

**Comment by Helios-lmh** [comment]
还是不行，想哭

**Comment by whtsky** [comment]
500 是内部服务器错误啊。 有更详细的日志吗

**Comment by Helios-lmh** [comment]
应该是这个了
 - [2017/08/10 18:08:14] - Traceback (most recent call last):
  File "/data1/www/htdocs/518/hang01/2/werobot/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/data1/www/htdocs/518/hang01/2/werobot/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/data1/www/htdocs/518/hang01/2/werobot/werobot/contrib/bottle.py", line 62, in werobot_view
    return robot.get_encrypted_reply(message)
  File "/data1/www/htdocs/518/hang01/2/werobot/werobot/robot.py", line 350, in get_encrypted_reply
    reply = self.get_reply(message)
  File "/data1/www/htdocs/518/hang01/2/werobot/werobot/robot.py", line 322, in get_reply
    session_storage = self.session_storage
  File "/data1/www/htdocs/518/hang01/2/werobot/werobot/utils.py", line 42, in wrapped_func
    setattr(self, prop_name, method(self, *args, **kwargs))
  File "/data1/www/htdocs/518/hang01/2/werobot/werobot/robot.py", line 115, in session_storage
    from .session.sqlitestorage import SQLiteStorage
  File "/data1/www/htdocs/518/hang01/2/werobot/werobot/session/sqlitestorage.py", line 5, in <module>
    import sqlite3
  File "/usr/local/sae/python/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/sae/python/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3  yq34

**Comment by whtsky** [comment]
不用 Session 可以关掉，要用的话可以用 SAEKVStorage

**Comment by Helios-lmh** [comment]
?什么意思，我没有用session呀。

**Comment by whtsky** [comment]
默认是开的。使用前请详细阅读文档

**Comment by Helios-lmh** [comment]
嗯嗯，好的。多谢您的耐心解答！
