### ISSUE TITLE
client.get_media_list问题

### ISSUE THREAD

**Issue by zjw0358** [whtsky/WeRoBot#236]
client.get_media_list ，传入参数错误，目前代码如下：
data={
                "type": media_type,
                "offset": offset,
                "count": count
            }

提交请求如 client.get_media_list("video",0,1)，
会报错ClientException: 40004: invalid media type hint: [6X8n0140e298]

修改为如下时可正常访问：

data=_json.dumps({
                "type": media_type,
                "offset": offset,
                "count": count
            })

**Comment by helloqiu** [comment]
试了一下，无法复现。
