### ISSUE TITLE
No handlers could be found for logger "WeRoBot"

### ISSUE THREAD

**Issue by dengxuesong** [whtsky/WeRoBot#248]
No handlers could be found for logger "WeRoBot"

在一些消息处理中会出现 这个提示，确认了代码没问题
@robot.subscribe
def subscribe(msg):
    print msg, type(msg)
    print msg.source
    u = User.query.filter_by(openid=msg.source).first()
    if u is None:
        u = User(msg.source, 1)
        u.save()
    else:
        u.status = 1
        u.save(True)
     return "111"

**Comment by helloqiu** [comment]
1. 请正确缩进
2. 请提供足够的 log
3. 如果 ```return "111"``` 是在 ```else``` 里面的话，如果新建 User 会没有 Reply，没有 Reply 就会认为这个 handler 没有处理这个 message
