### ISSUE TITLE
Flask与WeRobot集成

### ISSUE THREAD

**Issue by Decalogue** [whtsky/WeRoBot#249]
您好！
我在服务器上部署Flask与WeRobot是按照您的示例代码写的，在微信公众平台提交url配置是成功的，但是好像无法收到消息。请问默认配置除了token外其他要修改哪些参数才能成功呢？（我是购买的百度BAE的服务器。）
多谢了！

**Comment by whtsky** [comment]
麻烦贴一下运行日志。
常见原因是把 WeRoBot 挂载到了 `/robot/` 路径，但是在微信后台填写的路径是 `/robot` （没有最后的 `/` ）

**Comment by Decalogue** [comment]
您好！已经解决了。谢谢您的提示。上次按照您的建议改写的。
具体出错的地方是加密模式下服务器端没有正常安装cryptography的依赖。已经在BAE提交工单了。感觉项目文档非常清晰，具体模块非常好用，谢谢分享！
