### ISSUE TITLE
关于创建菜单失败的问题

### ISSUE THREAD

**Issue by Tianyingxing** [whtsky/WeRoBot#265]
调用了client创建菜单的api
client.create_menu({
    "button":[
        {
            "type":"click",
            "name":"今日歌曲",
            "key":"V1001_TODAY_MUSIC"
        },
        {
            "type":"click",
            "name":"歌手简介",
            "key":"V1001_TODAY_SINGER"
        },
        {
            "name":"菜单",
            "sub_button":[
                {
                    "type":"view",
                    "name":"搜索",
                    "url":"http://www.soso.com/"
                },
                {
                    "type":"view",
                    "name":"视频",
                    "url":"http://v.qq.com/"
                },
                {
                    "type":"click",
                    "name":"赞一下我们",
                    "key":"V1001_GOOD"
                }
            ]
        }
    ]})

可是我在公众号上，依然看不到菜单栏。

**Comment by whtsky** [comment]
有报错吗

**Comment by Tianyingxing** [comment]
没有报错，只是在公众号上不出现菜单栏，设定的文本处理函数，倒是生效了，发文字过去的，接受到相应的处理后的回复。

**Comment by Tianyingxing** [comment]
出现了，不知道什么原因，昨晚一直不出现，但是今天早上试了试，在公众号，可以看到菜单了

**Comment by TsangTsingYuan** [comment]
一样是调用了client创建菜单的api，报错：werobot.client.ClientException: 41002: appid missing hint: [TRv.oA0422sha2]
