### ISSUE TITLE
How to use HTTPS

### ISSUE THREAD

**Issue by JasonLeeSJTU** [whtsky/WeRoBot#266]
I want to use **https** for the host, but the following config results in a **http** host: http://127.0.0.1:443

`robot.config['HOST'] = '127.0.0.1'
robot.config['PORT'] = 443`

**This leads to error:**
Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.

So, how to config https host with 443 port?

**Comment by helloqiu** [comment]
I recommend using `Nginx` or other reliable server as reverse proxy.You can config nginx as a **HTTPS** server and pass request to the proxied server which in this case is werobot.
https://www.nginx.com/resources/admin-guide/reverse-proxy/
http://nginx.org/en/docs/http/configuring_https_servers.html
