### ISSUE TITLE
想改gunicorn timeout不知道如何操作

### ISSUE THREAD

**Issue by leon-ye** [whtsky/WeRoBot#267]
用gunicorn，由于用爬虫访问的网页，会在晚上10点后，需要用vpn才能连接，而我没有，所以之后发送请求会超过默认30s，一般10点之后要1分钟才返回503error，所以想改gunicorn timeout的时间，不知道如何操作，求解答

**Comment by helloqiu** [comment]
http://docs.gunicorn.org/en/latest/settings.html?highlight=timeout#timeout

**Comment by leon-ye** [comment]
这个我知道，是这样，我的模块名是app，变量名是robot 用命令gunicorn --time 60 app:robot,监听的是8000，报错connection in use:('127.0.0.1',8000)我把监听进程kill掉之后，然后用gunicorn --time 60 app:robot，还是一样，然后看了下，监听自动打开了
