### ISSUE TITLE
发现一处小问题

### ISSUE THREAD

**Issue by yuangezhizao** [whtsky/WeRoBot#269]
[https://github.com/whtsky/WeRoBot/blob/develop/werobot/session/mysqlstorage.py#L34](https://github.com/whtsky/WeRoBot/blob/develop/werobot/session/mysqlstorage.py#L34)
```
        session_storage = mysqlstorage.MySQLStorage(
```
应该是这样吧
```
        session_storage = MySQLStorage(
```

**Comment by helloqiu** [comment]
感谢反馈
