### ISSUE TITLE
请问现在微信access_token超时失效后，是怎么处理的？

### ISSUE THREAD

**Issue by yangsongx** [whtsky/WeRoBot#282]
当隔一段时间，再使用client.xxxx()时候，会报40001: invalid credential, access_token is invalid or not latest hint:的错误。

看起来是Werobot启动时候获取的微信access_token超时失效了。

不知道Werobot内部怎么更新access_token?目前没找到什么接口来更新access_token

**Comment by whtsky** [comment]
一般来说是其他客户端刷了 access_token 导致的。
更新接口参考文档
