### ISSUE TITLE
能不能支持发送模板消息接口？

### ISSUE THREAD

**Issue by huyx** [whtsky/WeRoBot#69]
模板消息用于公众号向用户发送重要的服务通知，参见：

http://mp.weixin.qq.com/wiki/17/304c1885ea66dbedf7dc170d84999a9d.html

**Comment by whtsky** [comment]
高三党，近一个月内没时间动这个…欢迎 fork 后实现，然后发 PR ..Sent using CloudMagicOn 周日, 1月 11, 2015 at 8:46 下午,  huyx <notifications@github.com> wrote:            模板消息用于公众号向用户发送重要的服务通知，参见：

http://mp.weixin.qq.com/wiki/17/304c1885ea66dbedf7dc170d84999a9d.html
