### ISSUE TITLE
有没有可能加入向指定用户发送微信的接口？

### ISSUE THREAD

**Issue by khalilleo** [whtsky/WeRoBot#70]
如题，谢谢 ：）

**Comment by keviswang** [comment]
可以呀。。调用客服接口就可以呀。

**Comment by khalilleo** [comment]
不好意思没有说清楚，有没有可能不用客服接口来发微信呢？因为客服接口貌似有时间限制

**Comment by fangwentong** [comment]
@khalilleo 自己去看看微信公众平台的文档就知道能不能了.

微信公众平台可以被动向用户发送消息， 若想主动发送消息，需调用客服接口或者高级群发接口.

为了避免公众号滥发消息， 微信仅开放这几个接口是合理的.

**Comment by khalilleo** [comment]
谢谢回复：）
