### ISSUE TITLE
请问，用户关注时，如何返回带html的文本？

### ISSUE THREAD

**Issue by openpython** [whtsky/WeRoBot#74]
请问，用户关注时，如何返回带html的文本？很多微信号被关注时都返回有网址链接和笑脸图标的文本。

**Comment by tg123** [comment]
网址链接可以 使用 `<a>` 标签 这个对话就可以解析的

**Comment by openpython** [comment]
试验了<a>标签可用，<br/><p>类的标签无效，怎么排版？

**Comment by openpython** [comment]
试验了a标签可用，

br,p类的标签无效，怎么排版？
