### ISSUE TITLE
如何把接收微信映射的地址下面的目录，做其他的函数处理？

### ISSUE THREAD

**Issue by csufuyi** [whtsky/WeRoBot#75]
robot.py 中校验get方法的部分如下，我想对同样的freesz.sinaapp.com/douban这样的子目录做不同的响应函数，该如何在外部设置呢？
    @property
    def wsgi(self):
        if not self._handlers:
            raise
        app = Bottle()

        @app.get('<t:path>')
        def echo(t):
            if not self.check_signature(
                request.query.timestamp,
                request.query.nonce,
                request.query.signature
            ):
                return abort(403)
            return request.query.echostr

尝试这样做无效：
  import sae
from robot import robot

@robot.wsgi.get('/douban')
def douban():
    print 'from douban'
    return 'douban'

application = sae.create_wsgi_app(robot.wsgi)

**Comment by tg123** [comment]
```
robot = your robot app
app   = your webapp inst
app.mount('/api', robot.wsgi)

@app.get('/douban')
def douban():

```

**Comment by csufuyi** [comment]
thanks~~~~~
