### ISSUE TITLE
使用application.mount 部署到sae上报错 AttributeError: 'function' object has no attribute 'mount' 

### ISSUE THREAD

**Issue by csufuyi** [whtsky/WeRoBot#76]
sae本地部署是OK的，deploy到sae后运行报错

index.wsgi如下：
from bottle import Bottle, request, run
from weixin import wxrobot
from douban import client

import sae

application = sae.create_wsgi_app(wxrobot.wsgi)

import sys
print sys.path

application.mount('/api', wxrobot.wsgi)

@application.get('/douban')
def douban():
    code = request.GET.get('code', None)
    print code
    client.auth_with_code(code)
    print client.token_code
    print 'from douban'
    return "oauth begin"

怀疑是名字冲突，打印了path：

 ['/data1/www/htdocs/708/freesz/1/site-packages', 
'/data1/www/htdocs/708/freesz/1', 
'/usr/local/sae/python/lib/python27.zip', 
'/usr/local/sae/python/lib/python2.7', 
'/usr/local/sae/python/lib/python2.7/plat-linux2', 
'/usr/local/sae/python/lib/python2.7/lib-tk', 
'/usr/local/sae/python/lib/python2.7/lib-old', 
'/usr/local/sae/python/lib/python2.7/lib-dynload',
 '/usr/local/sae/python/lib/python2.7/site-packages'

**Comment by tg123** [comment]
先创建一个 bottle 的 app 
然后把 werobot mount 上去

然后 把 app 扔给 sae 就好了

```
app = webapp
app.mount('/api', robot.wsgi)

application = sae.create_wsgi_app(app)
```

**Comment by csufuyi** [comment]
非常感谢~~折腾了一圈，是自己对mount理解不深，搞定了~
