### ISSUE TITLE
@robot.text, @robot.filter 不能同时使用

### ISSUE THREAD

**Issue by evilerliang** [whtsky/WeRoBot#77]
问题如上，这样在区分一般文本消息和关键字消息很棘手，为什么不先过滤，最后将其他消息返回

**Comment by tg123** [comment]
filter 是 text 的 包装 本质是一个东西

你能说下 不能同时用是什么 意思 没有理解

**Comment by evilerliang** [comment]
```Python
# todo:这个接口会捕获所有的文本消息，十分蛋疼
@robot.text
def text(message):
    return '这是一个文本消息'
@robot.filter('test')
def test():
    text = '真是机智啊，让你发现了这个彩蛋，嘿嘿~~~'
    return text
```

也就是说两种handler同时使用`@robot.text`会被优先调用使`@robot.filter('test')`失效

**Comment by whtsky** [comment]
把彩蛋那个函数放在返回所有文本信息的函数前面就好了。


Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On 周六, 5月 16, 2015 at 1:11 上午, erliang <notifications@github.com> wrote:
问题如上，这样在区分一般文本消息和关键字消息很棘手，为什么不先过滤，最后将其他消息返回
