### ISSUE TITLE
Git管理代码怎么部署到GAE

### ISSUE THREAD

**Issue by adrianzhang** [whtsky/WeRoBot#80]
不幸在没遇到WeRoBot的时候就使用了Git来管理GAE代码，根据GAE规定不能使用（也就是后台不支持）Git和SVN两种工具混合管理代码。于是，当按照https://github.com/whtsky/WeRoBot-SAE-demo的README.md一步步在本地部署完毕后，没法部署到SAE上。
有谁能给指点指点如何用Git完成SAE的部署？先谢！

**Comment by tg123** [comment]
GAE 还是 SAE

**Comment by whtsky** [comment]
其实你可以删掉 .git 文件夹然后用 SVN 部署的…

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On 周四, 8月 20, 2015 at 1:06 上午, whtsky/WeRoBot
<reply@reply.github.com>
wrote:
不幸在没遇到WeRoBot的时候就使用了Git来管理GAE代码，根据GAE规定不能使用（也就是后台不支持）Git和SVN两种工具混合管理代码。于是，当按照 https://github.com/whtsky/WeRoBot-SAE-demo的README.md一步步在本地部署完毕后，没法部署到SAE上。
[https://github.com/whtsky/WeRoBot-SAE-demo%E7%9A%84README.md%E4%B8%80%E6%AD%A5%E6%AD%A5%E5%9C%A8%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2%E5%AE%8C%E6%AF%95%E5%90%8E%EF%BC%8C%E6%B2%A1%E6%B3%95%E9%83%A8%E7%BD%B2%E5%88%B0SAE%E4%B8%8A%E3%80%82]
有谁能给指点指点如何用Git完成SAE的部署？先谢！

**Comment by adrianzhang** [comment]
谢谢两位。是SAE。SAE代码管理只支持Git或SVN其中一种，不能同时用，所以一旦我使用了git就不能再用svn管理了。正在新建一个应用，由于一些原因需要点时间。我会后续post相关进展。

**Comment by adrianzhang** [comment]
这些天发现，使用docker来搭建个服务器比较方便，不像SAE那么多管制，而且有DaoCloud.io这样的云服务商基于docker提供服务。很好。现在应用跑在他家主机上。
