### ISSUE TITLE
非常奇怪的不支持tuple问题

### ISSUE THREAD

**Issue by adrianzhang** [whtsky/WeRoBot#82]
写了个程序，主要两个文件 index.py和 myfunc.py

在myfunc.py里有个类Aclass，这个类有个方法xxx，这个方法里有这么一句：
`params = urllib.urlencode((('text', text_content), ('from', source), ('to', target)))`
其中`text_content`, `source`, `target`都是字符串变量，假设值分别为abc, www, ppp

写了个text.py，**text.py里没有使用werobot**，调用Aclass.xxx()的时候，params正确显示为`text=somecharacters(somecharacters是abc做了encode后的正确内容)&from=www&to=ppp`

index.py里**使用了werobot**，且不调用Aclass.xxx()的时候，已经调试通过，使用
`@robot.text`
`def suibian(message):`
可以正确响应微信用户发来的消息
而一旦在suibian这个函数里调用了Aclass.xxx()，params奇怪地成为了：
`text=%3Cwerobot.messages.TextMessage+object+at+0x2639e90%3E&from=www&to=ppp`

也就是说，对比起来，本来的`soemcharacters`成了`%3Cwerobot.messages.TextMessage+object+at+0x2639e90%3E`
从而导致了index.py运行与test.py不一样，也就是无法达到想要的功能。

**Comment by adrianzhang** [comment]
再次测试发现，原因出在将`message`赋值给`text_content`
那么`text_content`的内容就不是微信用户发来的信息，而是`<werobot.messages.TextMessage object at 0x27bbed0>`

**Comment by whtsky** [comment]
用 message.content

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On 周二, 9月 1, 2015 at 7:07 上午, Adrian Zhang <notifications@github.com> wrote:
再次测试发现，原因出在将 message 赋值给 text_content
那么 text_content 的内容就不是微信用户发来的信息，而是 <werobot.messages.TextMessage object at 0x27bbed0>

—
Reply to this email directly or view it on GitHub
[https://github.com/whtsky/WeRoBot/issues/82#issuecomment-136524002] .[https://github.com/notifications/beacon/AA1gloRlgR0r3CwfuBXaKhEffl7X2OSuks5otNWfgaJpZM4F1GlD.gif]

**Comment by adrianzhang** [comment]
谢谢！用message.content解决了问题。这个issue可以close了。

**Comment by whtsky** [comment]
你 close 吧，我在军训没时间开电脑…
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On 周二, 9月 1, 2015 at 8:28 上午, Adrian Zhang <notifications@github.com> wrote:
谢谢！用message.content解决了问题。这个issue可以close了。

—
Reply to this email directly or view it on GitHub
[https://github.com/whtsky/WeRoBot/issues/82#issuecomment-136536530] .[https://github.com/notifications/beacon/AA1gllNczQbrrEWSPEaxSoLfz2rFDOOcks5otOikgaJpZM4F1GlD.gif]
