### ISSUE TITLE
当使用werobot，收到消息后若处理需要时间超过5秒，则无法返回处理后的消息给微信后台。

### ISSUE THREAD

**Issue by adrianzhang** [whtsky/WeRoBot#83]
写成如下形式：
```
@robot.text
def text_voice(message):
    生成voice，上传到某个url。产生两个变量a和b。
    a = '描述'
    b = "http://.........(音乐URL)"
    print (a)
    print (b)
    return ['名称', a, b]
```
能正确打印出a和b的字符串内容。然而，return之后并未发出任何消息。

**Comment by adrianzhang** [comment]
经过测试。如果没有“生成voice，上传到某个URL。”这个步骤，是可以返回音乐消息的。一旦有了那个步骤，就不返回。哪怕改写成`return ['a', 'b', 'c']`都不行，非常奇怪！

**Comment by adrianzhang** [comment]
一步步检查，发现只要调用了一个类和方法，GET某个url生成文件保存到本地，return语句就不起作用，无论是return 文本还是音乐。而这个类和方法的调用，拿出来单独测试是通过的。

**Comment by adrianzhang** [comment]
只要调用的方法里用到了requests，就不返回。

**Comment by adrianzhang** [comment]
最终确定：只要调用一个类的方法里有写入文件的操作，就不能得到return。跟调用方法里用requests 或 httplib都没关系。

**Comment by whtsky** [comment]
能贴下示例代码嘛？

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On 周日, 9月 6, 2015 at 11:45 下午, Adrian Zhang <notifications@github.com> wrote:
最终确定：只要调用一个类的方法里有写入文件的操作，就不能得到return。跟调用方法里用requests 或 httplib都没关系。

—
Reply to this email directly or view it on GitHub
[https://github.com/whtsky/WeRoBot/issues/83#issuecomment-138094313] .[https://github.com/notifications/beacon/AA1glp0uX6gnR91E3m_YtLGc9HM-cHIlks5ovFchgaJpZM4F4k33.gif]

**Comment by adrianzhang** [comment]
```
import my

@robot.text
def text_voice(message):
    x = my.classM(key)
    y = x.savefile('abc','en')
    a = '描述'
    b = "http://.........(音乐URL)"
    print (a)
    print (b)
    return ['名称', a, b]

文件my:


class classM():
	def __init__(self, key):
		self.key = key

	def savefile(self, text, lang):
		req = {'key':self.key, 'src':text, 'hl':lang}
		r = requests.get("https://api.voiceservice.com/", params=req, stream=True)
		if r.status_code == 200:
			with open('tts.mp3', 'wb') as output_file:
				for chunk in r.iter_content():
					output_file.write(chunk)
				return ('ok')
		else:
			print (r.text)
			return (r.text)
```

**Comment by adrianzhang** [comment]
savefile 方法里，随便干什么，只要涉及写文件，主文件里就无法return一个text或music

**Comment by adrianzhang** [comment]
改写类和方法，改成调用七牛fetch API，还是不return  快要疯掉了！ 现在的类和方法不涉及在本地存储，只不过是http的发送和接收， 这样也不行？？！

**Comment by whtsky** [comment]
我感觉不是 WeRoBot 的锅啊

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On 周一, 9月 7, 2015 at 8:36 下午, Adrian Zhang <notifications@github.com> wrote:
改写类和方法，改成调用七牛fetch API，还是不return 快要疯掉了！ 现在的类和方法不涉及在本地存储，只不过是http的发送和接收， 这样也不行？？！

—
Reply to this email directly or view it on GitHub
[https://github.com/whtsky/WeRoBot/issues/83#issuecomment-138285754] .[https://github.com/notifications/beacon/AA1glqXalbZFVLWfcpWzhhVDlTdjdW38ks5ovXxVgaJpZM4F4k33.gif]

**Comment by adrianzhang** [comment]
这些类和方法，单独使用一个文件去调用运行都是没问题的。只要放到
```
@robot.txt
def some_func(message)
.....

**Comment by adrianzhang** [comment]
这些类和方法用别的单独文件调用都是没问题的。就不能放到下面这样的包装中。不用，return 'abc'是工作的，一旦用了就没有xml消息send出来。
```
@robot.txt
def some_fun(message):
    调用方法
   return 'abc'
```

**Comment by adrianzhang** [comment]
werobot服务端也没有任何异常报错。

**Comment by fangwentong** [comment]
应该是savefile阻塞时间太长, 超过了5s

网络流传输过程建议使用异步IO

**Comment by adrianzhang** [comment]
@fangwentong 

啊呀呀，我简直泪流满面。要是两个小时前看到你的回复我就不会浪费两个小时得出同样的结论了。
经过设置断点跟踪，确认werobot正确生成了reply的xml消息给wsgi网关。

两次问题中，对微信发过来的request处理的时间都到达了10s，因此怀疑是wsgi有超时限制断掉了给request发响应。之前使用的wsgi是cherrypy，后换成tornado，也不行。试图在cherrypy源代码里把超时的设置改掉，改了半天还是不生效。在网上溜达找方法的时候，发现了[这个帖子][1]详细地讲述了wsgi关于超时设置的考虑。

正一筹莫展的时候看到了你的回复。目前情况是：@robot.text 得到了消息后，才能处理消息，先处理成文字，再去调用API生成语音，处理成文字很快，但是调用API就慢了。而对这个text消息做出的响应是语音。那么这样一个过程该如何实现异步呢？

[1]: http://stackoverflow.com/questions/3679537/downtime-when-reloading-mod-wsgi-daemon/3682085#3682085

**Comment by fangwentong** [comment]
@adrianzhang  关于被动回复用户信息的文档    
<http://mp.weixin.qq.com/wiki/14/89b871b5466b19b3efa4ada8e577d45e.html>

具体地说，问题不是因为wsgi超时时间过小， 而是微信服务器等待接口返回的时间为5s


看起来，你可能不必从voiceservice下载音频， 然后再将转存的音频地址发给用户， 可以尝试将https://api.voiceservice.com/key=xxx&dsrc=xxx&hl=xxx 作为音乐的URL， 让微信客户端从直接从voice service provider 获取， 不知是否可行。

不知10s的等待是因为网速慢， 还是voice service文字转语音速度慢， 看样子是要换服务商了

**Comment by adrianzhang** [comment]
@fangwentong 感谢回复。
文字转语音服务需要时间的，任何一个service都需要这个时间，文字越长时间越长。即便让微信直接send url，处理时间也轻易超过了5s。
所以我的思路是：当用户发来文字信息，先快速处理，但不给回复或回复空消息。这是函数a，代码如下：
```
@robot.text
def a(message):
    do something
    return ' '     #还没测试return None是否可行。
```
然后，考虑把a函数处理的文本和url作为入口参数调用主动发消息。但是这里就不知道该怎么做了。疑惑主要在于：函数a已经处理了@robot.text事件了。那么用什么传递给下一个函数呢？存到文件里或放入数据库？写成下面这样？
```
import werobot
robot = werobot.WeRoBot(token='werobotbackend', enable_session=True)
@robot.text
def a(message):
    do something
    write text to a file
    return ""

signal = f.open('temp.txt')
content =signal.read()
f.close()

while content != None:
    convert content to voice(call related function)
    url = returned media url
from werobot.client import Client
client = Client('id', 'secret')
mediaid = client.upload('voice', mediaFile)
client.send_voice_message('id', mediaid)

robot.run(server='cherrypy',host='0.0.0.0',port=80)
```
问题是，从while开始到send_voice_message这段代码是怎么触发的？

**Comment by adrianzhang** [comment]
@fangwentong 

此外，我是用一个微信模拟器测试后端，能够看到后端是否发出响应。所以，并不是微信那边超时5s断掉，而是这个微信后端压根就没送出xml格式的消息。

**Comment by adrianzhang** [comment]
试图把处理语音并单独调用发送消息那段代码写成一个函数，然后用celery等消息队列处理，但还是会等待。很奇怪。代码如下：
```
@robot.text
def a(message):
    do something
    write text to a file
    q = Queue(connection=Redis())
    result = q.enqueue(func, message, text)
    return ""
```

**Comment by adrianzhang** [comment]
经过一番research，这个问题不是一个框架能够解决的。所有的框架性项目在遇到这类问题时候都无法完整处理。
