### ISSUE TITLE
再次pip install werobot后，代码没改，出现如下错误

### ISSUE THREAD

**Issue by adrianzhang** [whtsky/WeRoBot#84]
```
  File "index.py", line 13, in <module>
    robot = werobot.WeRoBot(token='testrobot', enable_session=True)
  File "/usr/local/lib/python2.7/site-packages/werobot/robot.py", line 47, in __init__
    filename=os.path.abspath("werobot_session")
  File "/usr/local/lib/python2.7/site-packages/werobot/session/filestorage.py", line 20, in __init__
    self.db = dbm.open(filename, "c")
  File "/usr/local/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/usr/local/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/usr/local/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb
```

**Comment by aetherwu** [comment]
把CentOS7.0上的Python2.7.5升级到2.7.10以后也出现了同样的问题：（

**Comment by aetherwu** [comment]
发现一个线索，但并不完全知道到底如何解决：
> You need to install Python --with-berkeley-db4 to enable bsddb support. It's not enabled by default.
> https://github.com/Homebrew/homebrew/issues/41948

**Comment by whtsky** [comment]
在包管理器里面搜一下有没有叫 "bsddb" 或者类似的包
然后重新编译一下 Python

**Comment by aetherwu** [comment]
@whtsky 嗯，昨晚上试过了，得到的结果是：
Collecting bsddb3
  Using cached bsddb3-6.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Can't find a local Berkeley DB installation.
    (suggestion: try the --berkeley-db=/path/to/bsddb option)

我猜过这个 db 是不是 werobot session （-berkeley-db=/root/wechat/werobot_session）。
结果并不是。。。对了，也许找找原来的那个 db？

**Comment by aetherwu** [comment]
被逼无赖之下我暂时先禁止了 session。
enable_session=False

我只是很好奇为啥它会请求这个 bsddb 。。。哼。。。

**Comment by whtsky** [comment]
@aetherwu 在操作系统的包管理器里搜。
这种情况是你自己编译 Python 的时候没有装 bsddb 造成的。
默认的基于文件的 Session 存储是用 bsddb 实现的
