### ISSUE TITLE
如何响应普通的http请求呢？

### ISSUE THREAD

**Issue by yijunjun** [whtsky/WeRoBot#89]
我想订阅号能在接受到外界普通的http请求，能够触发向一些微信号发送消息。

**Comment by whtsky** [comment]
用其他的 Web 框架处理 HTTP 请求。
可以用 https://github.com/whtsky/Django-WeRoBot 、
https://github.com/whtsky/Flask-WeRoBot 或者
https://github.com/whtsky/Tornado-WeRoBot 把 WeRoBot 集成在其他 Web 框架里面。

在 2015年12月16日 上午9:24，yijunjun <notifications@github.com>写道：
