### ISSUE TITLE
Session expiration

### ISSUE THREAD

**Issue by kilowu** [whtsky/WeRoBot#94]
现在的session似乎是永久存起来的，能否设置一个时间，自动过期？

**Comment by whtsky** [comment]
Pull Requests are welcomed.

**Comment by kilowu** [comment]
How about adding a keyword argument to WeRoRot ctor.
```Python
robot = werobot.WeRoBot(token='mytoken123', 
                                          enable_session=True, 
                                          session_expire_time=600, # 10 minutes
                                         )
```
In the background server loop, we can invoke another thread routinely expires the session at every session_expire_time seconds.

**Comment by whtsky** [comment]
@kilowu 这样灵活性似乎太差了啊。

我觉得把现在的
```python
def set(self, id, value)
```

改成

```python
def set(self, id, value, expires=None)
```
比较好，这样能手动控制 session 中每个值的储存时间。
